### ISSUE TITLE
Merge radial and normal progress

### ISSUE THREAD

**Issue by MonsieurMan** [SNCFdevelopers/wcs#56]
Should we merge radial and progress bar into one and passing a prop for the mode ?

```jsx
<wcs-progress mode="radial"></wcs-progress>
<wcs-progress mode="bar"></wcs-progress>
<!-- or -->
<wcs-progress-radial></wcs-progress-radial>
<wcs-progress-bar></wcs-progress-bar>
```

**Comment by Nexyll** [comment]
Given that the API of those two components are intended to be identical, I think it's a good idea.

**Comment by MonsieurMan** [comment]
Closing as the radial progress has a size properties that makes no sense on the bar progress.
